djangoProject1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject1 import settings

urlpatterns = [
path('', include('hrms.urls', namespace = 'hrms')),
    path('admin/', admin.site.urls),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path, reverse
from . import views
app_name = 'hrms'
urlpatterns = [

# Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('login_emp/', views.Login_View_Emp.as_view(), name='login_emp'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard_emp/', views.Dashboard_Emp.as_view(), name='dashboard_emp'),

    path('holidays', views.holidays_page, name="holidays_page"),
    path('delete_holiday/<int:holiday_id>/', views.delete_holiday, name="delete_holiday"),
    path('edit_holiday/<int:holiday_id>/', views.edit_holiday_page, name="edit_holiday_page"),

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),

#Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

#Leave Routes
path('leave_application_details/<int:id>/', views.leave_application_details,
         name="leave_application_details"),
    path('apply_leave/', views.apply_leave, name="apply_leave"),
    path("dashboard/leave/new/", views.leave_dashboard_page, name="leave_new"),
    path('approve_leave/', views.approve_leave, name="approve_leave"),
    path('reject_leave/', views.reject_leave, name="reject_leave"),

#Recruitment

    path('manage_job_advertisement_page', views.manage_job_advertisement_page, name="manage_job_advertisement_page"),
    path('edit_job_advertisement_page/<int:job_advertisement_id>/', views.edit_job_advertisement_page,
         name="edit_job_advertisement_page"),
    path('delete_job_advertisement/<int:job_advertisement_id>/', views.delete_job_advertisement,
         name="delete_job_advertisement"),
    path('recruitment', views.job_advertisements_page, name="job_advertisements_page"),
    path('view_job_applications_page', views.view_job_applications_page, name="view_job_applications_page"),
    path('job_advertisement/<int:job_advertisement_id>/', views.job_advertisement, name="job_advertisement"),
    path('job_applications/<int:job_advertisement_id>/', views.job_applications_page, name="job_applications"),
    path("recruitment1/",views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/",views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

#Payroll
    path("employee/pay/",views.Pay.as_view(), name="payroll")

]
def javascript_settings():
    js_conf = {
        'get_end_date': reverse('get_end_date'),
        'get_number_of_days_between_two_dates': reverse('get_number_of_days_between_two_dates'),
        'get_no_of_days': reverse('get_no_of_days'),
        'approve_leave': reverse('approve_leave'),
        'reject_leave': reverse('reject_leave'),
        'edit_leave_application': reverse('edit_leave_application'),
        'delete_leave_application': reverse('delete_leave_application'),
        'apply_leave_page': reverse('apply_leave_page'),
        'leave_dashboard_page': reverse('leave_dashboard_page'),
    }

    return js_conf

hrms/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, resolve_url, render
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import CreateView, View, DetailView, TemplateView, ListView, UpdateView, DeleteView

from .forms import RegistrationForm, LoginForm, EmployeeForm, DepartmentForm, AttendanceForm, LeaveForm, \
    RecruitmentForm, JobApplicationForm
from .models import Employee, Department, Attendance, Leave, Recruitment, create_holiday, get_all_holidays, get_holiday, \
    Holiday, JobAdvertisement, LeaveApplication
from .selector import get_job_advertisement
from .selector import get_job_applications
from .selector import get_all_job_ads, get_all_positions, get_position
from .selector import get_all_job_ads, get_all_positions, get_position


# Create your views here.
class Index(TemplateView):
    template_name = 'hrms/home/home.html'


#   Authentication
class Register(CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = 'hrms/registrations/register.html'
    success_url = reverse_lazy('hrms:login')


class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/login.html'
    redirect_authenticated_user = False

    def get_success_url(self):
        url = resolve_url('hrms:dashboard')
        return url


class Login_View_Emp(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/emp_login.html'
    redirect_authenticated_user = False

    def get_success_url(self):
        url = resolve_url('hrms:dashboard_emp')
        return url


class Logout_View(View):

    def get(self, request):
        logout(self.request)
        return redirect('hrms:login', permanent=True)


# Main Board
class Dashboard(LoginRequiredMixin, ListView):
    template_name = 'hrms/dashboard/index.html'
    login_url = 'hrms:login'
    model = get_user_model()
    context_object_name = 'qset'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.all().count()
        context['workers'] = Employee.objects.order_by('-id')
        return context


class Dashboard_Emp(LoginRequiredMixin, ListView):
    template_name = 'hrms/dashboard/emp_index.html'
    login_url = 'hrms:login'
    model = get_user_model()
    context_object_name = 'qset'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.all().count()
        context['workers'] = Employee.objects.order_by('-id')
        return context


# Employee's Controller
class Employee_New(LoginRequiredMixin, CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'hrms/employee/create.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'


class Employee_All(LoginRequiredMixin, ListView):
    template_name = 'hrms/employee/index.html'
    model = Employee
    login_url = 'hrms:login'
    context_object_name = 'employees'
    paginate_by = 5


class Employee_View(LoginRequiredMixin, DetailView):
    queryset = Employee.objects.select_related('department')
    template_name = 'hrms/employee/single.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            return context
        except ObjectDoesNotExist:
            return context


class Employee_Update(LoginRequiredMixin, UpdateView):
    model = Employee
    template_name = 'hrms/employee/edit.html'
    form_class = EmployeeForm
    login_url = 'hrms:login'


class Employee_Delete(LoginRequiredMixin, DeleteView):
    pass


# Department views

class Department_Detail(LoginRequiredMixin, ListView):
    context_object_name = 'employees'
    template_name = 'hrms/department/single.html'
    login_url = 'hrms:login'

    def get_queryset(self):
        queryset = Employee.objects.filter(department=self.kwargs['pk'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dept"] = Department.objects.get(pk=self.kwargs['pk'])
        return context


class Department_New(LoginRequiredMixin, CreateView):
    model = Department
    template_name = 'hrms/department/create.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'


class Department_Update(LoginRequiredMixin, UpdateView):
    model = Department
    template_name = 'hrms/department/edit.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:dashboard')


# Attendance View

class Attendance_New(LoginRequiredMixin, CreateView):
    model = Attendance
    form_class = AttendanceForm
    login_url = 'hrms:login'
    template_name = 'hrms/attendance/create.html'
    success_url = reverse_lazy('hrms:attendance_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["today"] = timezone.localdate()
        pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q(date=timezone.localdate()))
        context['present_staffers'] = pstaff
        return context


class Attendance_Out(LoginRequiredMixin, View):
    login_url = 'hrms:login'

    def get(self, request, *args, **kwargs):
        user = Attendance.objects.get(
            Q(staff__id=self.kwargs['pk']) & Q(status='PRESENT') & Q(date=timezone.localdate()))
        user.last_out = timezone.localtime()
        user.save()
        return redirect('hrms:attendance_new')


class LeaveNew(LoginRequiredMixin, CreateView, ListView):
    model = Leave
    template_name = 'hrms/leave/create.html'
    form_class = LeaveForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:leave_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["leaves"] = Leave.objects.all()
        return context


class Payroll(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'hrms/payroll/index.html'
    login_url = 'hrms:login'
    context_object_name = 'stfpay'


class RecruitmentNew(CreateView):
    model = Recruitment
    template_name = 'hrms/recruitment/index.html'
    form_class = RecruitmentForm
    success_url = reverse_lazy('hrms:recruitment')


class RecruitmentAll(LoginRequiredMixin, ListView):
    model = Recruitment
    login_url = 'hrms:login'
    template_name = 'hrms/recruitment/all.html'
    context_object_name = 'recruit'


class RecruitmentDelete(LoginRequiredMixin, View):
    login_url = 'hrms:login'

    def get(self, request, pk):
        form_app = Recruitment.objects.get(pk=pk)
        form_app.delete()
        return redirect('hrms:recruitmentall', permanent=True)


class Pay(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'hrms/payroll/index.html'
    context_object_name = 'emps'
    login_url = 'hrms:login'


def holidays_page(request):
    if request.POST:
        date = request.POST.get('date')
        name = request.POST.get('name')
        holiday = create_holiday(date, name)
        messages.success(request, "Successfully created the holiday")
        return HttpResponseRedirect(reverse('hrms:holidays_page'))

    holidays = get_all_holidays()
    context = {
        "holidays_page": "active",
        "holidays": holidays
    }

    return render(request, 'hrms/holiday/holidays_page.html', context)


def get_current_year():
    return datetime.datetime.now().year


def get_leave_record(email, year):
    try:
        leave_record = LeaveApplication.objects.get(email=email, leave_year=year)
        return leave_record
    except Exception:
        return None


def delete_holiday(request, holiday_id):
    holiday = get_holiday(holiday_id)
    holiday.delete()
    messages.success(request, "Deleted a holiday entry")
    return HttpResponseRedirect(reverse('hrms:holidays_page'))


def edit_holiday_page(request, holiday_id):
    holiday = get_holiday(holiday_id)
    if request.POST:
        date = request.POST.get('date')
        name = request.POST.get('name')
        Holiday.objects.filter(id=holiday.id).update(
            name=name,
            date=date
        )
        messages.success(request, "Updated the holiday entry")
        return HttpResponseRedirect(reverse('hrms:holidays_page'))
    context = {
        "holidays_page": "active",
        "holiday": holiday
    }
    return render(request, 'hrms/holiday/edit_holiday.html', context)


def manage_job_advertisement_page(request):
    if request.POST:
        position_id = request.POST.get('position_id')
        position = get_position(position_id)
        education = request.POST.get('education')
        vacancy = request.POST.get('vacancy')
        experience = request.POST.get('experience')
        description = request.POST.get('description')
        deadline = request.POST.get('deadline')

        JobAdvertisement.objects.create(
            position=position,
            education=education,
            vacancy=vacancy,
            experience=experience,
            description=description,
            deadline=deadline
        )

hrms/templates/hrms/employee/create.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} New Employee |HRMS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-plus">&emsp; New Employee </i></h4><hr>
                                <form enctype="multipart/form-data" action="{% url 'hrms:employee_new' %}" class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small>
                                        {{form.as_p}}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success"><i class="mdi mdi-file-document"></i>Add Employee</button></button>
                                        
                                    </div>
                                </form>
                        
                                           
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

hrms/templates/hrms/employee/edit.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Edit Employee |HRMS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
            <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'hrms:dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page"><a href=" {% url 'hrms:employee_all' %} ">Employee</a> </li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-edit">&emsp; Edit Employee </i></h4><hr>
                                <form enctype="multipart/form-data" class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small>
                                        {{form.as_p}}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success btn-rounded"><i class="mdi mdi-cloud-download"></i>Update Employee</button></button>
                                        
                                    </div>
                                </form>                   
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

hrms/templates/hrms/employee/index.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} All Employees |HRMS {% endblock title %}
      <!--  MAIN BODY START HERE -->
          {% block content %}

      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="row">
            <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'hrms:dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Employee </li>
                        <li class="breadcrumb-item active" aria-current="page">All</li>
                    </ol>
                </nav>
            <div class="col-lg-12 grid-margin">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">All Employees<a href="{% url 'hrms:employee_new' %}" class="btn btn-sm btn-success mb-3 float-right">Add New +</a></h4>
                    
                  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>
                            Thumbnail
                          </th>
                          <th>
                            First name
                          </th>
                          <th>
                            Last name
                          </th>
                          <th>
                            Telephone
                          </th>
                          <th>
                            E-mail
                          </th> 
                          <th>
                            Actions
                          </th>                         
                        </tr>
                      </thead>
                      <tbody>
                      {% for employee in employees  %}
                        <tr>
                          <td class="font-weight-medium">
                            <img src="{{employee.thumb.url}}" class='rounded img-fluid' alt="">
                          </td>
                          <td>
                            {{employee.first_name}}
                          </td>
                          <td>
                            {{employee.last_name}}
                          </td>
                          <td>
                           {{employee.mobile}}
                          </td>
                          <td class="text-danger"> 
                            {{employee.email}}
                          </td>
                          <td>
                          
                            <div class="btn-group dropdown">
                              <button type="button" class="btn btn-success dropdown-toggle btn-rounded btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               <i class="fa fa-cog "></i> Manage
                              </button>
                              <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'hrms:employee_view' pk=employee.pk %}">
                                  <i class="fa fa-eye text-success fa-fw"></i>View</a>
                                <a class="dropdown-item" href="{% url 'hrms:employee_update' pk=employee.pk %}">
                                  <i class="fa fa-edit text-info fa-fw"></i>Edit</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'hrms:employee_delete' pk=employee.pk %}">
                                  <i class="fa fa-trash text-danger fa-fw"></i>Delete</a>
                              </div>
                            </div>                  
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>

                    {% if is_paginated %}
                      <nav aria-label="Page navigation example" class='mt-4'>
                        <ul class="pagination">
                        {% if page_obj.has_previous %}
                          <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                        {% else %}

                          <li class="page-item disabled"><span class='page-link '>Previous</span></li>
                        {% endif %}
                          <li class="disabled"> <span class='page-link'> Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} </span></li>
                        {% if page_obj.has_next %}
                          <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                        {% else %}
                          <li class="page-item disabled"><span class='page-link '>Next</span></li> 
                        {% endif %}                        
                        </ul>
                    </nav>
                    {% endif %}
                
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        {% block noty %}
        <script>
          {% if messages %}
            {% for message in messages  %}
              toastr.success('{{message}}')
            {% endfor %}
          {% endif %}
        </script>
        {% endblock noty %}
        {% endblock content %}

hrms/templates/hrms/employee/single.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Employee's Info | ITSC-HRMS {% endblock title %}
{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'hrms:dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page"><a href=" {% url 'hrms:employee_all' %} ">Employee</a> </li>
                        <li class="breadcrumb-item active" aria-current="page">View</li>
                    </ol>
                </nav>
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-address-book-o">&emsp; Employee's Profile</i></h4><hr>   
                           <div class="row">
                                <div class="col-lg-2 col-md-2 d-flex align-items-stretch grid-margin">

                                    <div class="card border-top border-bottom border-success">
                                        <div class="card-body">
                                            <img src="{{employee.thumb.url}}" alt="" class="img-fluid" width='200px' height='200px'>
                                            <p class="lead mt-2 text-center"> 
                                            {{employee.emp_id | capfirst}} <br>
                                            <small class='text-center text-secondary'>( ID )</small>
                                             </p>
                                            
                                        </div>
                                    </div>

                                
                                </div>
                                    <!-- Second column -->
                                <div class="col-lg-6 col-md-6">
                                    <div class="table-responsive border-top border-success table-striped">
                                        <p class="lead text-center mt-2">Personal Info.</p>
                                        <table class="table">
                                        <tr>
                                            <th style="width:50%">First Name:</th>
                                            <td>{{employee.first_name}}</td>
                                        </tr>
                                        <tr>
                                            <th>Last Name</th>
                                            <td>{{employee.last_name}}</td>
                                        </tr>
                                        <tr>
                                            <th>Mobile:</th>
                                            <td>{{employee.mobile}}</td>
                                        </tr>
                                        <tr>
                                            <th>Email:</th>
                                            <td>{{employee.email}}</td>
                                        </tr>
                                         <tr>
                                            <th>Gender:</th>
                                            <td>{{employee.gender}}</td>
                                        </tr>
                                        <tr>
                                            <th>Department:</th>
                                            <td>{{employee.department}} Unit</td>
                                        </tr>
                                        <tr>
                                            <th>Language:</th>
                                            <td>{{employee.language | capfirst}}</td>
                                        </tr>
                                         <tr>
                                            <th>Monthly Salary:</th>
                                            <td>#{{employee.salary}}</td>
                                        </tr>
                                         <tr>
                                            <th>Enrollment Date:</th>
                                            <td>{{employee.joined}} </td>
                                        </tr>
                                        <tr>
                                            <th>Number:</th>
                                            <td>{{employee.number}} </td>
                                        </tr>
                                        <tr>
                                            <th>Bank:</th>
                                            <td>{{employee.bank}} </td>
                                            
                                        </tr>
                                        
                                        </table>
                                        <div class="text-center mt-3">
                                            <a href=" {% url 'hrms:employee_update' pk=employee.id %}" class="btn btn-lg btn-warning">Update</a>
                                        </div>
                                    </div>   
                                </div>
                           </div>                     
                                        
                </div>
            </div>
        </div>
    </div>
        </div>
    </div>
{% endblock content %}