djangoProject1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject1 import settings

urlpatterns = [
path('', include('hrms.urls', namespace = 'hrms')),
    path('admin/', admin.site.urls),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path, reverse
from . import views
app_name = 'hrms'
urlpatterns = [

# Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('login_emp/', views.Login_View_Emp.as_view(), name='login_emp'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard_emp/', views.Dashboard_Emp.as_view(), name='dashboard_emp'),

    path('holidays', views.holidays_page, name="holidays_page"),
    path('delete_holiday/<int:holiday_id>/', views.delete_holiday, name="delete_holiday"),
    path('edit_holiday/<int:holiday_id>/', views.edit_holiday_page, name="edit_holiday_page"),

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),

#Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

#Leave Routes
path('leave_application_details/<int:id>/', views.leave_application_details,
         name="leave_application_details"),
    path('apply_leave/', views.apply_leave, name="apply_leave"),
    path("dashboard/leave/new/", views.leave_dashboard_page, name="leave_new"),
    path('approve_leave/', views.approve_leave, name="approve_leave"),
    path('reject_leave/', views.reject_leave, name="reject_leave"),

#Recruitment

    path('manage_job_advertisement_page', views.manage_job_advertisement_page, name="manage_job_advertisement_page"),
    path('edit_job_advertisement_page/<int:job_advertisement_id>/', views.edit_job_advertisement_page,
         name="edit_job_advertisement_page"),
    path('delete_job_advertisement/<int:job_advertisement_id>/', views.delete_job_advertisement,
         name="delete_job_advertisement"),
    path('recruitment', views.job_advertisements_page, name="job_advertisements_page"),
    path('view_job_applications_page', views.view_job_applications_page, name="view_job_applications_page"),
    path('job_advertisement/<int:job_advertisement_id>/', views.job_advertisement, name="job_advertisement"),
    path('job_applications/<int:job_advertisement_id>/', views.job_applications_page, name="job_applications"),
    path("recruitment1/",views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/",views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

#Payroll
    path("employee/pay/",views.Pay.as_view(), name="payroll")

]
def javascript_settings():
    js_conf = {
        'get_end_date': reverse('get_end_date'),
        'get_number_of_days_between_two_dates': reverse('get_number_of_days_between_two_dates'),
        'get_no_of_days': reverse('get_no_of_days'),
        'approve_leave': reverse('approve_leave'),
        'reject_leave': reverse('reject_leave'),
        'edit_leave_application': reverse('edit_leave_application'),
        'delete_leave_application': reverse('delete_leave_application'),
        'apply_leave_page': reverse('apply_leave_page'),
        'leave_dashboard_page': reverse('leave_dashboard_page'),
    }

    return js_conf

hrms/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, resolve_url, render
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import CreateView, View, DetailView, TemplateView, ListView, UpdateView, DeleteView

from .forms import RegistrationForm, LoginForm, EmployeeForm, DepartmentForm, AttendanceForm, LeaveForm, \
    RecruitmentForm, JobApplicationForm
from .models import Employee, Department, Attendance, Leave, Recruitment, create_holiday, get_all_holidays, get_holiday, \
    Holiday, JobAdvertisement, LeaveApplication
from .selector import get_job_advertisement
from .selector import get_job_applications
from .selector import get_all_job_ads, get_all_positions, get_position
from .selector import get_all_job_ads, get_all_positions, get_position


# Create your views here.
class Index(TemplateView):
    template_name = 'hrms/home/home.html'


#   Authentication
class Register(CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = 'hrms/registrations/register.html'
    success_url = reverse_lazy('hrms:login')


class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/login.html'
    redirect_authenticated_user = False

    def get_success_url(self):
        url = resolve_url('hrms:dashboard')
        return url


class Login_View_Emp(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/emp_login.html'
    redirect_authenticated_user = False

    def get_success_url(self):
        url = resolve_url('hrms:dashboard_emp')
        return url


class Logout_View(View):

    def get(self, request):
        logout(self.request)
        return redirect('hrms:login', permanent=True)


# Main Board
class Dashboard(LoginRequiredMixin, ListView):
    template_name = 'hrms/dashboard/index.html'
    login_url = 'hrms:login'
    model = get_user_model()
    context_object_name = 'qset'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.all().count()
        context['workers'] = Employee.objects.order_by('-id')
        return context


class Dashboard_Emp(LoginRequiredMixin, ListView):
    template_name = 'hrms/dashboard/emp_index.html'
    login_url = 'hrms:login'
    model = get_user_model()
    context_object_name = 'qset'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.all().count()
        context['workers'] = Employee.objects.order_by('-id')
        return context


# Employee's Controller
class Employee_New(LoginRequiredMixin, CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'hrms/employee/create.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'


class Employee_All(LoginRequiredMixin, ListView):
    template_name = 'hrms/employee/index.html'
    model = Employee
    login_url = 'hrms:login'
    context_object_name = 'employees'
    paginate_by = 5


class Employee_View(LoginRequiredMixin, DetailView):
    queryset = Employee.objects.select_related('department')
    template_name = 'hrms/employee/single.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            return context
        except ObjectDoesNotExist:
            return context


class Employee_Update(LoginRequiredMixin, UpdateView):
    model = Employee
    template_name = 'hrms/employee/edit.html'
    form_class = EmployeeForm
    login_url = 'hrms:login'


class Employee_Delete(LoginRequiredMixin, DeleteView):
    pass


# Department views

class Department_Detail(LoginRequiredMixin, ListView):
    context_object_name = 'employees'
    template_name = 'hrms/department/single.html'
    login_url = 'hrms:login'

    def get_queryset(self):
        queryset = Employee.objects.filter(department=self.kwargs['pk'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dept"] = Department.objects.get(pk=self.kwargs['pk'])
        return context


class Department_New(LoginRequiredMixin, CreateView):
    model = Department
    template_name = 'hrms/department/create.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'


class Department_Update(LoginRequiredMixin, UpdateView):
    model = Department
    template_name = 'hrms/department/edit.html'
    form_class = DepartmentForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:dashboard')


# Attendance View

class Attendance_New(LoginRequiredMixin, CreateView):
    model = Attendance
    form_class = AttendanceForm
    login_url = 'hrms:login'
    template_name = 'hrms/attendance/create.html'
    success_url = reverse_lazy('hrms:attendance_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["today"] = timezone.localdate()
        pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q(date=timezone.localdate()))
        context['present_staffers'] = pstaff
        return context


class Attendance_Out(LoginRequiredMixin, View):
    login_url = 'hrms:login'

    def get(self, request, *args, **kwargs):
        user = Attendance.objects.get(
            Q(staff__id=self.kwargs['pk']) & Q(status='PRESENT') & Q(date=timezone.localdate()))
        user.last_out = timezone.localtime()
        user.save()
        return redirect('hrms:attendance_new')


class LeaveNew(LoginRequiredMixin, CreateView, ListView):
    model = Leave
    template_name = 'hrms/leave/create.html'
    form_class = LeaveForm
    login_url = 'hrms:login'
    success_url = reverse_lazy('hrms:leave_new')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["leaves"] = Leave.objects.all()
        return context


class Payroll(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'hrms/payroll/index.html'
    login_url = 'hrms:login'
    context_object_name = 'stfpay'


class RecruitmentNew(CreateView):
    model = Recruitment
    template_name = 'hrms/recruitment/index.html'
    form_class = RecruitmentForm
    success_url = reverse_lazy('hrms:recruitment')


class RecruitmentAll(LoginRequiredMixin, ListView):
    model = Recruitment
    login_url = 'hrms:login'
    template_name = 'hrms/recruitment/all.html'
    context_object_name = 'recruit'


class RecruitmentDelete(LoginRequiredMixin, View):
    login_url = 'hrms:login'

    def get(self, request, pk):
        form_app = Recruitment.objects.get(pk=pk)
        form_app.delete()
        return redirect('hrms:recruitmentall', permanent=True)


class Pay(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'hrms/payroll/index.html'
    context_object_name = 'emps'
    login_url = 'hrms:login'


def holidays_page(request):
    if request.POST:
        date = request.POST.get('date')
        name = request.POST.get('name')
        holiday = create_holiday(date, name)
        messages.success(request, "Successfully created the holiday")
        return HttpResponseRedirect(reverse('hrms:holidays_page'))

    holidays = get_all_holidays()
    context = {
        "holidays_page": "active",
        "holidays": holidays
    }

    return render(request, 'hrms/holiday/holidays_page.html', context)


def get_current_year():
    return datetime.datetime.now().year


def get_leave_record(email, year):
    try:
        leave_record = LeaveApplication.objects.get(email=email, leave_year=year)
        return leave_record
    except Exception:
        return None


def delete_holiday(request, holiday_id):
    holiday = get_holiday(holiday_id)
    holiday.delete()
    messages.success(request, "Deleted a holiday entry")
    return HttpResponseRedirect(reverse('hrms:holidays_page'))


def edit_holiday_page(request, holiday_id):
    holiday = get_holiday(holiday_id)
    if request.POST:
        date = request.POST.get('date')
        name = request.POST.get('name')
        Holiday.objects.filter(id=holiday.id).update(
            name=name,
            date=date
        )
        messages.success(request, "Updated the holiday entry")
        return HttpResponseRedirect(reverse('hrms:holidays_page'))
    context = {
        "holidays_page": "active",
        "holiday": holiday
    }
    return render(request, 'hrms/holiday/edit_holiday.html', context)


def manage_job_advertisement_page(request):
    if request.POST:
        position_id = request.POST.get('position_id')
        position = get_position(position_id)
        education = request.POST.get('education')
        vacancy = request.POST.get('vacancy')
        experience = request.POST.get('experience')
        description = request.POST.get('description')
        deadline = request.POST.get('deadline')

        JobAdvertisement.objects.create(
            position=position,
            education=education,
            vacancy=vacancy,
            experience=experience,
            description=description,
            deadline=deadline
        )

hrms/templates/hrms/emp_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title  %}{% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %} ">
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/font-awesome/css/font-awesome.css' %} ">


  <link rel="stylesheet" href="{% static 'hrms/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'hrms/css/toastr.min.css' %}">
  <link rel="shortcut icon" href="{% static 'hrms/images/favicon.png' %}" />
</head>

<body>
  <div class="container-scroller">
    {% include "hrms/nav.html" %}
    <div class="container-fluid page-body-wrapper">
      {% include 'hrms/emp_sidebar.html' %}
        {% block content %} {% endblock content %}

    </div>
  </div>
  <!-- plugins:js -->

  <script src="{% static 'hrms/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'hrms/vendors/js/vendor.bundle.addons.js' %}"></script>
  <script src="{% static 'hrms/js/toastr.min.js' %}"></script>
  <script src="{% static 'hrms/js/sweetalert2@8.js' %}"></script>
  <script src="{% static 'hrms/js/pay.js' %}"></script>


  {% block noty %}
  {% endblock noty %}
</body>

</html>

hrms/templates/hrms/emp_sidebar.html
<nav class="sidebar sidebar-offcanvas bg-facebook" id="sidebar" >
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <img src="{{user.thumb.url}}">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{user.username | upper}} </p>
                  <div>
                    <small class="designation text-muted">Employee</small>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:dashboard_emp' %}">
              <i class="fa  fa-dashboard"></i>
              <span class="menu-title">&emsp;Dashboard</span>
            </a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:apply_leave' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Leave</span>
            </a>
          </li>

        </ul>
      </nav>

hrms/templates/hrms/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title  %}{% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %} ">
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/font-awesome/css/font-awesome.css' %} ">
 
  
  <link rel="stylesheet" href="{% static 'hrms/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'hrms/css/toastr.min.css' %}">
  <link rel="shortcut icon" href="{% static 'hrms/images/favicon.png' %}" />
</head>
  
<body>
  <div class="container-scroller">
    {% include "hrms/nav.html" %}
    <div class="container-fluid page-body-wrapper">
      {% include 'hrms/sidebar.html' %}
        {% block content %} {% endblock content %}

    </div>
  </div>
  <!-- plugins:js -->
  
  <script src="{% static 'hrms/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'hrms/vendors/js/vendor.bundle.addons.js' %}"></script>
  <script src="{% static 'hrms/js/toastr.min.js' %}"></script>
  <script src="{% static 'hrms/js/sweetalert2@8.js' %}"></script>
  <script src="{% static 'hrms/js/pay.js' %}"></script>


  {% block noty %}
  {% endblock noty %}
</body>

</html>

hrms/templates/hrms/nav.html
    {% load static %}
    <nav class="navbar default-layout bg-success col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center bg-dark">
        <p class="display-4 mt-3 text-success">HRMS</p>
        <a class="navbar-brand brand-logo-mini" href="{% url 'hrms:dashboard' %}">
          <img src="{{user.thumb.url}}" />
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center bg-dark">
        
        <ul class="navbar-nav navbar-nav-right">          
          <li class="nav-item dropdown d-none d-xl-inline-block">
          
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text"> Hello, {{user.username | upper }} ! </span>
              <img class="img-xs rounded-circle" src=" {{user.thumb.url}} " alt="Profile image">
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">

              <a class="dropdown-item" href='{% url 'hrms:logout' %}'>
                Log Out
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

hrms/templates/hrms/sidebar.html
<nav class="sidebar sidebar-offcanvas bg-facebook" id="sidebar" >
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <img src="{{user.thumb.url}}">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{user.username | upper}} </p>
                  <div>
                    <small class="designation text-muted">Admin</small>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
              </div>
              <a href="{% url 'hrms:employee_new' %}" class="btn btn-primary btn-block">New Staff
                <i class="mdi mdi-plus"></i>
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:dashboard' %}">
              <i class="fa  fa-dashboard"></i>
              <span class="menu-title">&emsp;Dashboard</span>
            </a>
          </li>
         <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:holidays_page' %}">
              <i class="fa  fa-calendar"></i>
              <span class="menu-title">&emsp;Holidays</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:employee_all' %}" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-user text-dark"></i>
              <span class="menu-title">&emsp;Employee</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:attendance_new' %}">
              <i class="fa fa-calendar"></i>
              <span class="menu-title">&emsp;Attendance</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:leave_new' %}">
              <i class="fa fa-sign-out "></i>
              <span class="menu-title">&emsp;Leave</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-folder "></i>
              <span class="menu-title">&emsp;Department</span>
              <i class="menu-arrow"></i>
            <hr>

            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
              {% for dept in depts  %}
                <li class="nav-item">
                  <a class="nav-link" href="{{dept.get_absolute_url}}">{{dept.name}}</a>
                </li>
              {% endfor %}
              </ul>
            </div>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:manage_job_advertisement_page' %}">
              <i class="fa fa-database"></i>
              <span class="menu-title">&emsp;Recruitment</span>
            </a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:view_job_applications_page' %}">
              <i class="fa fa-database"></i>
              <span class="menu-title">&emsp;View Job Applications</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:payroll' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Leave</span>
            </a>
          </li>

        </ul>
      </nav>